name: CI/CD para a API Python do Desafio

on:
  push:
    branches: ["main"]

jobs:
  call-build-and-deploy-template:
    # Aponta para o nosso template reutilizável
    uses: LuanCristopher/github-ci-templates/.github/workflows/build-and-push-template.yml@main
    with:
      # O nome da imagem Docker
      image-name: 'ilia-desafio-api'
      # O caminho para o Dockerfile (a raiz do projeto)
      repo-path: '.' 
      # A tag da imagem (o hash do commit)
      tag: ${{ github.sha }}
      # CORREÇÃO: Adicionando o parâmetro que faltava
      language: 'python'
    secrets:
      # Passa os segredos necessários para o template
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      PAT_GIT_GITOPS: ${{ secrets.PAT_GIT_GITOPS }}