name: CI/CD - API Python (ECR + GitOps)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    uses: LuanCristopher/github-ci-templates/.github/workflows/build-and-push-template.yml@main
    with:
      image-name: "ilia-desafio-api"
      gitops-repo: "https://github.com/LuanCristopher/helm-charts-ilia.git"
      gitops-branch: "main"
      gitops-values-path: "api/values.yaml"
      gitops-image-repo-key: ".image.repository"
      gitops-image-tag-key: ".image.tag"
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PAT_GIT_GITOPS: ${{ secrets.PAT_GIT_GITOPS }}

#trigger