name: CI/CD para a API Python do Desafio

on:
  push:
    branches: ["main"]

jobs:
  call-build-and-deploy-template:
    # Aponta para o nosso template reutiliz치vel que j치 funciona
    uses: LuanCristopher/github-ci-templates/.github/workflows/build-and-push-template.yml@main
    with:
      # Define um nome para a imagem Docker que ser치 criada
      image-name: 'ilia-desafio-api'
    secrets:
      # Passa os segredos necess치rios para o template
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      PAT_GIT_GITOPS: ${{ secrets.PAT_GIT_GITOPS }}